
name: Adding Environment Variables

on: 
  workflow_dispatch: 

env: 
  DAY_OF_THE_WEEK: Tuesday
  testvar: value-1
  
jobs:
  mainjob:
    name: 'Print Evnironment Variables'
    runs-on: ubuntu-latest

    env:
      Greeting: Dear
      Second_Var: value-2

    steps:
    - name: print-values-of-env-variables
      run: |
        echo "$Greeting $First_Name. Today is $DAY_OF_THE_WEEK!"
        echo "local testvar $testvar"
        echo "Var from global ${{ env.Second_Var }}"
      env:
        First_Name: Student
        testvar: value-3
      
  custom_ENV_VAR:
    runs-on: ubuntu-latest
    steps:
    - name: 'Set Up Env Var Dynamically'
      run: 
        echo "dynamic_var=value-4" >> $ENV_VAR

    - name: 'Use the new Variable'
      run: 
        echo "${{ env.dynamic_var }}"







