
name: Adding Environment Variables

on: 
  push:
    branches: [ "main" ]

    # Workflow runs only when a change happens in a file in in this path
    # paths: [ ".github/*" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch: 

env: 
  DAY_OF_THE_WEEK: Tuesday
  testvar: value-1
  
jobs:
  mainjob:
    name: 'Print Evnironment Variables'
    runs-on: ubuntu latest

    env:
      Greeting: Dear
      testvar: value-2

    steps:
    - name: print-values-of-env-variables
      run:
        echo "$Greeting @First_Name. Today is $DAY_OF_THE_WEEK!"
        echo "local testvar $testvar"
        echo "global testvar ${{ env.testvar }}"
      env:
        First_Name: Student
        testvar: value-3

