
name: Adding Environment Variables

on: 
  workflow_dispatch: 

env: 
  DAY_OF_THE_WEEK: Tuesday
  testvar: value-1
  
jobs:
  mainjob:
    name: 'Print Evnironment Variables'
    runs-on: ubuntu-latest

    env:
      Greeting: Dear
      testvar: value-2

    steps:
    - name: print-values-of-env-variables
      run:
        echo "$Greeting @First_Name. Today is $DAY_OF_THE_WEEK!"
        echo "local testvar $testvar"
        echo "global testvar ${{ env.testvar }}"
      env:
        First_Name: Student
        testvar: value-3

