name: Artifacts

on: push

jobs:
  job_1:
    name: Create Artifact
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is an artifact in the form of a text. The default store period for GitHub Artifacts is 90 days" > file.txt

      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: file.txt

  job_2:
    name: Download Artifact
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dowloaded-artifact
      - run: cat file.txt 
      
