name: GitHub Environments

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    environment:
      name: stable-int
      url: https://github.com

    steps:
      - name: 'Print Environment Secret'
        run: echo 'Stable Int Secret :\ ${{ secrets.STABLE_INT_SECRET }} \n'
             echo 'False Secret Ref :\ ${{ secrets.THIS_IS_NOT_A_SECRET }}'
              