name: Passing Values Betweeen Steps

on: 
  workflow_dispatch:

jobs:
  passing-values-bw-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up A Value
        run: echo "env_var=value-1" >> $GITHUB_ENV

      - name: Create variables using GitHub Commands
        id: var_source_step
        run: |
          echo "Creating Values"
          echo "::set-output name=repo_name::$GITHUB_REPOSITORY_OWNER"
          echo "::set-output name=my_name::Stef"
          echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
      
      - name: Reuse-Variable-Value
        run: |
          echo "Print Values"
          echo variable env_var should be value-1 :: ${{ env.env_var }}
          echo variable repo_name should be my github repo :: ${{ steps.var_source_step.outputs.repo_name }}
          echo variable my_name should be my Stef :: ${{ steps.var_source_step.outputs.my_name }}
          echo variable date should be the date and time the pipeline was triggered :: ${{ steps.var_source_step.outputs.date }}
           