name: GitHub Secrets

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]
  
  workflow_dispatch:
    
jobs:

  print-password:
    runs-on: ubuntu-latest
    steps: 
      - run: echo Repo Password ${{ secrets.MY_PASSWORD }}

